apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://lexfrei.github.io/charts"
    targetRevision: "0.2.0"
    chart: frame
    helm:
      values: |
        image:
          repository: "ghcr.io/lexfrei/worker"
          tag: "sha-0878789"
        env:
          REDIS_HOST: "redis-frame"
          PSQL_HOST: "db-frame"
        service:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
